Migliorie a kozajuge
gabrielegrillo/KozaJudge pull request #12
Opened 2023-11-17 12:58 UTC by ThaDome23

principalmente ho aggiunto la possibilità di specificare parametri a riga di comandi per mostrare l'input dei testcase
-i o --show_input mostra l'input dei testcase
se viene specificato -s o --small l'input viene mostrato su una sola riga

oltre a questo ho giusto pulito un po' il codice e aggiunto l'help a riga di comando

2023-11-17 20:55 UTC, gabrielegrillo requested changes
I testcase non devono stare sulla repo. Koza è per tutti non solo per studenti dell'unical

2023-11-17 20:56 UTC, gabrielegrillo commented on Exercises/Place_files_here.txt
Questo file non ha senso. Gli utenti devono leggere il readme

2023-11-17 22:29 UTC, ThaDome23 commented on Exercises/Place_files_here.txt
Si, lo avevo aggiunto dato che non avevo modificato il readme, quello va tolto.
Per quanto riguarda i testcase, li avevo aggiunti nella repo perchè così si poteva fare git clone e scaricare direttamente senza il zip

2023-11-20 08:58 UTC, PxycoSec commented
L'unica modifica utile può essere l'help. Per il resto le ulteriori modifiche non contribuiscono allo sviluppo del programma.

2023-11-23 17:34 UTC, closed without merging